name: linting
on: [push]
jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3 # получаем код
      - name: run yamllint
        uses: karancode/yamllint-github-action@v2.1.1
      - name: run ansible-lint
        uses: ansible/ansible-lint@main